### ISSUE TITLE
Cannot locate material file

### ISSUE THREAD

**Issue by stephengold** [capdevon/Archer-Game-Template#4]
When I build the application from a cloned repo, I see a "missing texture" displayed on each crate, and there's a diagnostic message on the console during startup:
```text
Nov 10, 2020 9:58:49 AM com.jme3.scene.plugins.ogre.SceneMaterialLoader startElement
WARNING: Cannot locate material file: Scenes/ManyLights/Scene.material
```
Perhaps the "Scene.material" asset isn't checked into the repository?

**Comment by capdevon** [comment]
The missing texture on each crate was deliberately a temporary choice.
https://github.com/capdevon/Archer-Game-Template/blob/fc441b586f3cd64fdb21de868fd634c99d76bedd/src/main/java/com/capdevon/util/PhysicsTestHelper.java#L59

I have added another texture to the project.

Scenes / ManyLights / Scene.material file is part of jme3-testdata.jar library, maybe we need to modify **build.gradle** file to add jme3-plugins library. Perhaps the **warning** depends on this configuration:

runtimeOnly 'org.jmonkeyengine:jme3-plugins:' + jmonkeyengineVersion

**Comment by stephengold** [comment]
Okay, that makes sense, except I'm not finding "Scene.material" in any recent version of "jme3-testdata.jar". I notice that the `TestManyLights` app in "jme3-examples" gives the same warning. It seems to be a harmless warning. I've opened [an issue](https://github.com/jMonkeyEngine/jmonkeyengine/issues/1420) against the Engine.
